exclude: ^data/

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    # Verify no new files over 500kb
    - id: check-added-large-files
    # Verify no merge conflict git markers are present
    - id: check-merge-conflict
    - id: check-case-conflict
    # Autocorrect mixed \n and \n\r line endings
    - id: mixed-line-ending
      args: ['--fix=lf']
    # Validate json files parse
    - id: check-json
    # Validate yaml files parse
    - id: check-yaml
    # Validate python files form valid AST
    - id: check-ast
    # Format json as human-readable
    - id: trailing-whitespace
    - id: pretty-format-json
      args: ['--autofix']

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      args: ['--multi-line=3', '--trailing-comma', '--force-grid-wrap=0', '--use-parentheses', '--line-width=100', '--honor-noqa']

-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      additional_dependencies: ['click==8.1.3']
      language_version: python3.9

-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports']